name: Schneider Architekten
favicon: null
layout_spectrum: 0.25093
typography_spectrum: 0.6720114049967378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98a6be'
    - '#5a718e'
    - '#e8cab2'
    - '#0a0000'
    - '#874f28'
  brandStrength: 0.5625
  lightness: 0.24053223244845867
  saturation: 0.27368699107319117
  rhythmicContrast: 0
purpose: []
