name: Schneider Architekten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98a6be'
    - '#5a718e'
    - '#e8cab2'
    - '#0a0000'
    - '#874f28'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
